OLCNE deployment fixes
oracle/vagrant-projects pull request #343
Opened 2021-02-14 15:02 UTC by denis256

Found that current OLCNE environment is not starting, showing bellow error:

```
  $ vagrant up
...
    master1:   "restrict-service-externalip-tls-cert" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-tls-key
    master1:   "restrict-service-externalip-tls-key" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-ca-cert
    master1:   "restrict-service-externalip-ca-cert" may not be empty

```

Added passing of
```
--restrict-service-externalip-ca-cert
--restrict-service-externalip-tls-cert
--restrict-service-externalip-tls-key
```
for each `--module kubernetes` invocation.

2021-02-14 16:14 UTC, AmedeeBulle commented
Linked to #342 
(Haven't reviewed yet -- just FYI)

2021-02-14 19:10 UTC, Djelibeybi commented
I believe @mark-au may have been looking into this as well.

2021-02-14 21:43 UTC, mark-au commented
I raised the GH Issue but hadn't made any codechanges yet, thanks for the PR and I'll test when there's a OCA

2021-02-15 06:42 UTC, denis256 commented
Hello,
I did OCA a while ago and my name is listed in https://www.oracle.com/technical-resources/oracle-contributor-agreement.html but it is for the FN project, should I redo it for vagrant-projects?

2021-02-15 08:55 UTC, AmedeeBulle commented
OCA is valid for all Oracle open-source projects, no need to re-submit.

2021-02-15 10:38 UTC, AmedeeBulle reviewed
@mark-au for comments...

- While the cluster comes up with this change, I don't think the `externalip-validation-webhook-service` service will work as it expects a certificate for the `externalip-validation-webhook-service.externalip-validation-system.svc[.cluster.local]` nodes. I would suggest creating an additional certificate instead of trying to reuse the existing one (it doesn't need to be replicated, it is only needed on the operator node)
- Alternatively, we could drop the `externalip-validation-webhook-service` service for the vagrant setup by using the `--restrict-service-externalip=false` parameter when we create the module

2021-02-15 20:46 UTC, rafabene approved these changes
I've tested and it worked.

2021-02-16 02:20 UTC, mark-au requested changes
I agree with @AmedeeBulle, we should use new certificates instead as per the docs to  [create the additional certificates](https://docs.oracle.com/en/operating-systems/olcne/obe-deploy-olcne/index.html#Set-up-Certificates-for-the-ex) and [create the module referencing these certificates](https://docs.oracle.com/en/operating-systems/olcne/obe-deploy-olcne/index.html#Add-the-Kubernetes-Module-to-t)

The Subject Alternative Name for the cert in this PR is `IP Address:127.0.0.1, IP Address:192.168.99.101, DNS:localhost` and likely would mean the `restrict-service-externalip` service fails on startup.

2021-03-02 07:18 UTC, Djelibeybi requested changes
Please update to use the documented process to create separate certificates.

2021-03-07 22:27 UTC, denis256 commented
Implemented generation of separated certificates for `externalip-validation-webhook` and distribution on cluster nodes

![image](https://user-images.githubusercontent.com/10694338/110257104-fc593180-7fa4-11eb-90cf-a3d25f5e7499.png)

2021-03-08 08:29 UTC, AmedeeBulle requested changes

2021-03-08 08:29 UTC, AmedeeBulle commented on OLCNE/scripts/provision.sh
> +readonly EXTERNALIP_VALIDATION_CERT_DIR=/etc/olcne/pki/externalip-validation-webhook
I don't think it is a great idea to have `EXTERNALIP_VALIDATION_CERT_DIR` as a sub-directory of the `CERT_DIR` directory (certificates at different levels in the hierarchy)

2021-03-08 08:29 UTC, AmedeeBulle commented on OLCNE/scripts/provision.sh
> +
My understanding is that the certificate for the externalIPs kubernetes service should only be on the operator node, there is no need for a transfer.
@mark-au to confirm

2021-03-10 18:07 UTC, denis256 commented
![image](https://user-images.githubusercontent.com/10694338/110676009-2e080d80-81dc-11eb-87f8-5cdfb48453ec.png)

2021-03-10 18:26 UTC, Djelibeybi approved these changes

2021-03-10 18:35 UTC, AmedeeBulle approved these changes
LGTM as well

2021-03-10 18:50 UTC, merged

2021-03-10 18:50 UTC, Djelibeybi commented
Thanks for your contribution!